<#
.SYNOPSIS
  Builds FRENCH_REVIEW.md from the shipped DefInjected XML, for TRANSLATIONS.md's
  "Systematic French review by Virginie" (2026-09-30).
.DESCRIPTION
  Reads every Mod/Languages/French/DefInjected/**/*.xml key. There is no Keyed folder and no
  separate Mod/Languages/English folder in this mod: English is the game's native fallback,
  read directly from the shipped Def in Mod/Defs (label/description resolved by dotted path
  against the Def's own XML). This mod is a continuation (Renew) of an upstream mod whose source
  text is English, so Original repeats English throughout; this file says so once here rather than on
  every row, per TRANSLATIONS.md section 3.
#>
param(
    [string]$Root = (Split-Path $PSScriptRoot -Parent),
    [string]$OutFile = (Join-Path (Split-Path $PSScriptRoot -Parent) 'FRENCH_REVIEW.md')
)

function Get-Entries($path) {
    $entries = [ordered]@{}
    if (-not (Test-Path $path)) { return $entries }
    $xml = [xml](Get-Content $path -Raw -Encoding UTF8)
    foreach ($node in $xml.LanguageData.ChildNodes) {
        if ($node.NodeType -ne 'Element') { continue }
        $entries[$node.Name] = $node.InnerText
    }
    return $entries
}

function Find-DefNode($nameOrDefName) {
    # Matches a ThingDef by its defName (concrete def) or its Name attribute (abstract base).
    if (-not $script:defCache.ContainsKey($nameOrDefName)) {
        $found = $null
        foreach ($f in $script:defFiles) {
            $x = [xml](Get-Content $f -Raw -Encoding UTF8)
            # Scoped to the def types the French files inject (ThingDef, ResearchProjectDef, ResearchTabDef): GraphicsDef and ThingDef nodes can share the same defName
            # (e.g. ASNeolithicHayPile), and only the ThingDef carries label/description.
            $node = $x.SelectSingleNode("//ThingDef[defName='$nameOrDefName' or @Name='$nameOrDefName'] | //ResearchProjectDef[defName='$nameOrDefName' or @Name='$nameOrDefName'] | //ResearchTabDef[defName='$nameOrDefName']")
            if ($node) { $found = $node; break }
        }
        $script:defCache[$nameOrDefName] = $found
    }
    return $script:defCache[$nameOrDefName]
}

function Resolve-Field($node, [string]$field) {
    # Reads $field on $node, or the nearest ancestor via ParentName if absent (RimWorld's own
    # inheritance): label/description are commonly declared once on an Abstract base ThingDef.
    $seen = @{}
    while ($node) {
        $val = $node.$field
        if ($val) { return [string]$val }
        $parentName = $node.GetAttribute('ParentName')
        if (-not $parentName -or $seen.ContainsKey($parentName)) { return $null }
        $seen[$parentName] = $true
        $node = Find-DefNode $parentName
    }
    return $null
}

function Resolve-DefField($defsRoot, [string]$key) {
    # key looks like "DefName.field" or "DefName.stages.N.field" or "DefName.tools.N.label"
    $parts = $key -split '\.'
    $defName = $parts[0]
    $rest = $parts[1..($parts.Length - 1)]
    $node = Find-DefNode $defName
    if (-not $node) { return $null }
    if ($rest.Count -eq 1) { return Resolve-Field $node $rest[0] }
    $cur = $node
    foreach ($p in $rest) {
        if ($cur -eq $null) { return $null }
        if ($p -match '^\d+$') {
            $children = @($cur.ChildNodes | Where-Object { $_.NodeType -eq 'Element' })
            $idx = [int]$p
            if ($idx -ge $children.Count) { return $null }
            $cur = $children[$idx]
        } else {
            $cur = $cur.$p
        }
    }
    if ($cur -is [System.Xml.XmlElement]) { return $cur.InnerText }
    if ($cur) { return [string]$cur }
    return $null
}

$frenchRoot = Join-Path $Root 'Mod/Languages/French/DefInjected'
$defsRoot = Join-Path $Root 'Mod/Defs'
$script:defFiles = Get-ChildItem $defsRoot -Recurse -Filter *.xml | ForEach-Object { $_.FullName }
$script:defCache = @{}

$frenchFiles = Get-ChildItem $frenchRoot -Recurse -Filter *.xml | Sort-Object FullName
$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine("# French review")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated by `scripts/Generate-FrenchReview.ps1` for TRANSLATIONS.md's systematic French review.")
[void]$out.AppendLine("**Original column: same as English throughout.** This mod is a continuation (Renew) of an upstream mod")
[void]$out.AppendLine("whose source text is English, so the Original column repeats the English column; there is no")
[void]$out.AppendLine("separate original-language field in this repository. No Keyed folder and no separate Mod/Languages/English folder exist:")
[void]$out.AppendLine("English is the game's native fallback, read directly from the shipped Defs.")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated $(Get-Date -Format 'yyyy-MM-dd'), revision: working tree after the owner's French corrections of 2026-10-08.")
[void]$out.AppendLine()

foreach ($ff in $frenchFiles) {
    $rel = $ff.FullName.Substring((Join-Path $Root 'Mod/Languages/French').Length + 1) -replace '\\', '/'
    $frEntries = Get-Entries $ff.FullName
    if ($frEntries.Count -eq 0) { continue }

    [void]$out.AppendLine("## $rel")
    [void]$out.AppendLine()
    [void]$out.AppendLine("| Key or path | Original | English | French |")
    [void]$out.AppendLine("|---|---|---|---|")
    foreach ($key in $frEntries.Keys) {
        $fr = $frEntries[$key]
        $orig = Resolve-DefField $defsRoot $key
        $en = $orig
        if ($null -eq $orig) { $orig = '*(not found — check by hand)*'; $en = '*(not found — check by hand)*' }
        $flag = if ($fr -match '\?\?\?|TODO|\{PAWN_gender' -and $fr -notmatch '\{PAWN_gender \? ') { ' | ?' } else { '' }
        $origCell = ($orig -replace '\|', '\|') -replace "`n", ' '
        $enCell = ($en -replace '\|', '\|') -replace "`n", ' '
        $frCell = ($fr -replace '\|', '\|') -replace "`n", ' '
        $keyCell = $key -replace '\|', '\|'
        [void]$out.AppendLine("| $keyCell | $origCell | $enCell | $frCell$flag |")
    }
    [void]$out.AppendLine()
}

[System.IO.File]::WriteAllText($OutFile, $out.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Output "wrote $OutFile"
